name: tathastu
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # Firebase Dependencies
  firebase_auth: ^0.15.3
  cloud_firestore: ^0.13.0+1
  # firebase_messaging: ^6.0.4
  # firebase_analytics: ^5.0.9
  # firebase_admob: ^0.9.0+10

  # State-management Dependencies
  provider: ^3.2.0

  # Design Dependencies
  google_fonts: ^0.2.0
  pin_code_fields: ^2.3.0+3
  flutter_svg: ^0.15.0
  flushbar: ^1.9.1
  datetime_picker_formfield: ^0.4.3
  http: ^0.12.0+2
  flutter_typeahead: ^1.7.0
  carousel_slider: ^1.3.1
  flutter_rating_bar: ^3.0.0+1
  # native_ads: ^0.3.0
  flutter_native_admob: ^0.1.1+2


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/city_onboarding_pink.svg
   - assets/data.svg
   - assets/hand.svg
   - assets/logo.svg
   - assets/male.svg
   - assets/female.svg
   - assets/icons/house.svg
   - assets/icons/analytics.svg
   - assets/icons/team.svg
   - assets/icons/contact.svg
   - assets/icons/key.svg
   - assets/icons/exit.svg
   - assets/icons/alarm.svg
   - assets/icons/clock.svg
   - assets/icons/couple.svg
   - assets/icons/classroom.svg
   - assets/icons/store.svg
   - assets/icons/job-search.svg
   - assets/icons/businessman.svg
   - assets/icons/directory.svg
   - assets/icons/law-book.svg
   - assets/icons/skills.svg
   - assets/icons/scroll.svg
   - assets/icons/right-arrow.svg
   - assets/icons/toolbox.svg
   - assets/icons/arrows.svg
   - assets/icons/health.svg
   - assets/icons/health_plus.svg
   - assets/icons/food.svg
   - assets/icons/entertainment.svg
   - assets/icons/consultant.svg
   - assets/icons/office.svg
   - assets/icons/shop.svg
   - assets/icons/more.svg
   - assets/icons/menu.svg
   - assets/icons/clipboard.svg
   - assets/icons/terms-and-conditions.svg
   - assets/icons/secure-data.svg
   - assets/icons/logout.svg
   - assets/icons/arrow_back.svg
   - assets/icons/ngo.svg

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
